PORT = "3000"
LENGTH_PORT = 5

TTL = "2"
LENGTH_TTL = 2

ERROR_PKT = "0000"
LIST_PKT = []
LENGTH_PKTID = 16

LENGTH_FILENAME = 100

LENGTH_QUERY = 20

LENGTH_SECTION_IPV4 = 3
LENGTH_SECTION_IPV6 = 4

LENGTH_PACK = 1024
LENGTH_NCHUNK = 5
LENGTH_NCHUNKS = 6

CODE_QUERY = "QUER"
CODE_ANSWER_QUERY = "AQUE"
CODE_NEAR = "NEAR"
CODE_ANSWER_NEAR = "ANEA"
CODE_DOWNLOAD = "RETR"
CODE_ANSWER_DOWNLOAD = "ARET"
CODE_LOGO = "LOGO"

FILE_COND = "FileCondivisi/"